# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: fdfbf79419fb194306a856d36caaf15911875d12fa2f754ea8ccb2012aaf38e984d6f85c4b8d46c2615165798ca35f0a44edf254903432e034df183d04464cea

test:
  secret_key_base: 842c915cf43f884f06d7a7dd826b41a642420a01ad490b07871c67a49bb121268665e3f40c2dc1905c8efe81ab12a29625c51cd19f985424ff56dd466fc5f5a3
  aws_access_key_id: AKIAR2EPABVDV7MHFBIA
  aws_secret_access_key: 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
# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: 1b351dc1d16333e9de4dbe2244fe17d127932daa3620a927963b6f7af26bf53fb3113698e9409f90c0a45e640b0d7f217961b8faf113e1db1882cb4011f579da
  aws_access_key_id: AKIAR2EPABVDV7MHFBIA
  aws_secret_access_key: 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
